name: Build Workflow

on:
  push:
    branches: '**'
  pull_request:

jobs:
  build:
    name: Build (C++${{ matrix.cpp-standard }}, ${{ matrix.config }})
    runs-on: windows-latest

    strategy:
      matrix:
        cpp-standard: [20, 23]
        config: [Debug, Release, MinSizeRel, RelWithDebInfo]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create environment variables
        run: |
          $commitSha = (git rev-parse --short $env:GITHUB_SHA)
          echo "GEECORE_COMMIT_SHA=${commitSha}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

          $config = "${{ matrix.config }}".ToLower()
          echo "GEECORE_PRETTY_CONFIG=${config}" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: |
          cmake `
            -DCMAKE_CXX_STANDARD=${{ matrix.cpp-standard }} `
            -DGEECORE_INSTALL=ON `
            -DGEECORE_EXTRA_WARNINGS=ON `
            -DGEECORE_TREAT_WARNINGS_AS_ERRORS=ON `
            ${{ github.workspace }}

      - name: Build
        working-directory: build
        run: |
          cmake `
            --build . `
            --config ${{ matrix.config }}
