name: Build Workflow

on:
  push:
    branches: '**'
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/**'
      - 'deps/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/**'
      - 'deps/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    name: Build (C++${{ matrix.cpp-standard }}, ${{ matrix.config }})
    runs-on: windows-latest

    strategy:
      matrix:
        cpp-standard: [23]
        config: [Debug, Release, MinSizeRel, RelWithDebInfo]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: |
          cmake `
            -DCMAKE_CXX_STANDARD=${{ matrix.cpp-standard }} `
            -DGEECORE_INSTALL=ON `
            -DGEECORE_BUILD_TESTS=ON `
            -DGEECORE_EXTRA_WARNINGS=ON `
            -DGEECORE_TREAT_WARNINGS_AS_ERRORS=ON `
            ${{ github.workspace }}

      - name: Build
        working-directory: build
        run: |
          cmake `
            --build . `
            --config ${{ matrix.config }}

      - name: Test
        working-directory: build/tests/${{ matrix.config }}
        run: ./Tests.exe --order rand --warn NoAssertions
