name: Format Workflow (C++)

on:
  push:
    branches: '**'
    paths:
      - '**.hpp'
      - '**.cpp'
      - '.clang-format'
      - '.github/workflows/clang-format.yml'
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '.clang-format'
      - '.github/workflows/clang-format.yml'

env:
  LLVM_VERSION: 17

jobs:
  format:
    name: Check the formatting (C++)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pin to a specific version
        run: |
          $latestChocoVersion = (Resolve-ChocoPackageVersion -TargetVersion $env:LLVM_VERSION -PackageName 'llvm')
          Install-ChocoPackage -PackageName llvm -ArgumentList '--allow-downgrade', '--version', $latestChocoVersion

      - name: Run clang-format
        env:
            GEECORE_COMMIT_BEFORE: ${{ github.event.pull_request.base.sha || github.event.before }}
            GEECORE_COMMIT_AFTER: ${{ github.sha }}
        run: |
          git `
            -c core.autocrlf=false `
            -c core.eol=lf `
            -c color.ui=always `
            clang-format `
              --style file `
              --diff $env:GEECORE_COMMIT_BEFORE $env:GEECORE_COMMIT_AFTER
